import type { Metadata } from "next";
import App from "./app";

export const metadata: Metadata = {
  title: "My Health",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <App>{children}</App>;
}
